export const meals = {
    breakfast: [
        { id: 'b1', name: 'Paneer Bhurji Toast', type: 'veg', calories: 350, protein: 18, carbs: 30, fats: 15, ingredients: ['Paneer 100g', 'Bread 2 slices', 'Vegs'], steps: ['Sauté paneer & vegs', 'Serve on toast'] },
        { id: 'b2', name: 'Vegetable Poha', type: 'veg', calories: 280, protein: 5, carbs: 50, fats: 6, ingredients: ['Poha 1.5 cups', 'Peanuts', 'Onion'], steps: ['Rinse poha', 'Cook with spices'] },
        { id: 'b3', name: 'Egg Bhurji & Roti', type: 'non-veg', calories: 320, protein: 20, carbs: 25, fats: 12, ingredients: ['Eggs 3', 'Roti 1', 'Onion'], steps: ['Scramble eggs', 'Serve with roti'] },
        { id: 'b4', name: 'Besan Chilla', type: 'veg', calories: 250, protein: 12, carbs: 35, fats: 8, ingredients: ['Besan 1 cup', 'Veggies', 'Curd'], steps: ['Make batter', 'Cook on pan'] },
        { id: 'b5', name: 'Idli Sambar', type: 'veg', calories: 300, protein: 10, carbs: 60, fats: 2, ingredients: ['Idli 3', 'Sambar 1 bowl'], steps: ['Steam idli', 'Serve with sambar'] },
        { id: 'b6', name: 'Masala Omelette', type: 'non-veg', calories: 350, protein: 22, carbs: 5, fats: 15, ingredients: ['Eggs 3', 'Veggies'], steps: ['Whisk & cook', 'Fold & serve'] },
        { id: 'b7', name: 'Methi Thepla', type: 'veg', calories: 320, protein: 8, carbs: 45, fats: 10, ingredients: ['Thepla 2', 'Curd'], steps: ['Knead dough', 'Cook paratha'] },
        { id: 'b8', name: 'Sprouts Salad', type: 'veg', calories: 200, protein: 15, carbs: 35, fats: 1, ingredients: ['Sprouts', 'Lemon', 'Veggies'], steps: ['Mix everything'] },
        { id: 'b9', name: 'Oats Upma', type: 'veg', calories: 280, protein: 8, carbs: 40, fats: 5, ingredients: ['Oats 1 cup', 'Veggies'], steps: ['Roast oats', 'Cook with veggies'] },
        { id: 'b10', name: 'Moong Dal Chilla', type: 'veg', calories: 260, protein: 14, carbs: 30, fats: 6, ingredients: ['Moong Dal Batter'], steps: ['Soak & grind dal', 'Cook pancakes'] },
        { id: 'b11', name: 'Aloo Paratha (Low Oil)', type: 'veg', calories: 350, protein: 6, carbs: 50, fats: 10, ingredients: ['Paratha 1 large', 'Curd'], steps: ['Stuff potato mix', 'Roast with less oil'] },
        { id: 'b12', name: 'Egg Sandwich', type: 'non-veg', calories: 320, protein: 18, carbs: 30, fats: 12, ingredients: ['Boiled Eggs 2', 'Bread 2 slices'], steps: ['Mash eggs', 'Make sandwich'] },
        { id: 'b13', name: 'Daliya Khichdi', type: 'veg', calories: 300, protein: 8, carbs: 50, fats: 5, ingredients: ['Broken Wheat', 'Veggies'], steps: ['Pressure cook daliya'] },
        { id: 'b14', name: 'Soya Keema Toast', type: 'veg', calories: 300, protein: 20, carbs: 30, fats: 8, ingredients: ['Soya granules', 'Bread'], steps: ['Cook spicy soya', 'Top on toast'] },
        { id: 'b15', name: 'Chicken Sandwich', type: 'non-veg', calories: 350, protein: 25, carbs: 30, fats: 10, ingredients: ['Chicken Breast', 'Bread'], steps: ['Shred chicken', 'Make sandwich'] },
        { id: 'b16', name: 'Rava Dosa', type: 'veg', calories: 300, protein: 6, carbs: 55, fats: 6, ingredients: ['Rava Dosa 2', 'Chutney'], steps: ['Make instant batter', 'Crisp on tawa'] },
        { id: 'b17', name: 'Uttapam', type: 'veg', calories: 280, protein: 8, carbs: 50, fats: 5, ingredients: ['Batter', 'Toppings'], steps: ['Thick dosa with veggies'] },
        { id: 'b18', name: 'Paneer Sandwich', type: 'veg', calories: 350, protein: 18, carbs: 35, fats: 12, ingredients: ['Paneer slice', 'Bread'], steps: ['Grill paneer sandwich'] },
        { id: 'b19', name: 'Scrambled Tofu', type: 'veg', calories: 250, protein: 20, carbs: 10, fats: 12, ingredients: ['Tofu 200g', 'Turmeric'], steps: ['Crumble & sauté tofu'] },
        { id: 'b20', name: 'Boiled Eggs & Fruit', type: 'non-veg', calories: 250, protein: 18, carbs: 20, fats: 10, ingredients: ['Eggs 3', 'Apple'], steps: ['Boil eggs', 'Slice fruit'] },
        { id: 'b21', name: 'Sabudana Khichdi', type: 'veg', calories: 350, protein: 4, carbs: 60, fats: 10, ingredients: ['Sabudana', 'Peanuts'], steps: ['Soak & cook tapioca'] },
        { id: 'b22', name: 'Bread Omelette', type: 'non-veg', calories: 350, protein: 18, carbs: 30, fats: 15, ingredients: ['Eggs 2', 'Bread 2'], steps: ['Classic street style'] },
        { id: 'b23', name: 'Vermicelli Upma', type: 'veg', calories: 300, protein: 6, carbs: 50, fats: 8, ingredients: ['Sewai', 'Veggies'], steps: ['Roast & boil vermicelli'] },
        { id: 'b24', name: 'Millet Porridge', type: 'veg', calories: 250, protein: 8, carbs: 45, fats: 4, ingredients: ['Millet Flour', 'Milk/Water'], steps: ['Cook ragi/bajra malt'] },
        { id: 'b25', name: 'Fruit Smoothie', type: 'veg', calories: 250, protein: 5, carbs: 50, fats: 2, ingredients: ['Banana', 'Berries', 'Yogurt'], steps: ['Blend all fruits'] }
    ],
    lunch: [
        { id: 'l1', name: 'Chicken Curry Rice', type: 'non-veg', calories: 500, protein: 30, carbs: 60, fats: 15, ingredients: ['Chicken 150g', 'Rice', 'Spices'], steps: ['Cook curry', 'Serve with rice'] },
        { id: 'l2', name: 'Rajma Chawal', type: 'veg', calories: 450, protein: 16, carbs: 70, fats: 10, ingredients: ['Rajma', 'Rice'], steps: ['Pressure cook beans', 'Serve hot'] },
        { id: 'l3', name: 'Fish Curry Rice', type: 'non-veg', calories: 480, protein: 35, carbs: 55, fats: 12, ingredients: ['Fish 150g', 'Rice'], steps: ['Simmer fish in curry'] },
        { id: 'l4', name: 'Dal Tadka Roti', type: 'veg', calories: 450, protein: 18, carbs: 65, fats: 12, ingredients: ['Dal', 'Roti 2', 'Sabzi'], steps: ['Full thali meal'] },
        { id: 'l5', name: 'Curd Rice', type: 'veg', calories: 350, protein: 8, carbs: 50, fats: 10, ingredients: ['Rice', 'Curd', 'Tadka'], steps: ['Mix curd & rice'] },
        { id: 'l6', name: 'Soya Pulao', type: 'veg', calories: 400, protein: 25, carbs: 50, fats: 10, ingredients: ['Soya Chunks', 'Rice'], steps: ['One pot meal'] },
        { id: 'l7', name: 'Chole Bhature (Light)', type: 'veg', calories: 550, protein: 18, carbs: 75, fats: 20, ingredients: ['Chickpeas', 'Bhatura 2'], steps: ['Favorite combo'] },
        { id: 'l8', name: 'Egg Curry Rice', type: 'non-veg', calories: 450, protein: 20, carbs: 55, fats: 15, ingredients: ['Eggs 2', 'Rice'], steps: ['Spicy egg gravy'] },
        { id: 'l9', name: 'Paneer Butter Masala', type: 'veg', calories: 500, protein: 20, carbs: 40, fats: 25, ingredients: ['Paneer', 'Butter Gravy', 'Roti'], steps: ['Rich gravy with roti'] },
        { id: 'l10', name: 'Bhindi Masala Roti', type: 'veg', calories: 350, protein: 8, carbs: 50, fats: 12, ingredients: ['Okra', 'Roti 2'], steps: ['Stir fry veggies'] },
        { id: 'l11', name: 'Chicken Biryani', type: 'non-veg', calories: 600, protein: 35, carbs: 70, fats: 18, ingredients: ['Chicken', 'Basmati Rice'], steps: ['Layered rice dish'] },
        { id: 'l12', name: 'Veg Biryani', type: 'veg', calories: 500, protein: 12, carbs: 75, fats: 15, ingredients: ['Mixed Veggies', 'Rice'], steps: ['Aromatic rice'] },
        { id: 'l13', name: 'Mutton Curry Rice', type: 'non-veg', calories: 600, protein: 35, carbs: 50, fats: 25, ingredients: ['Mutton 150g', 'Rice'], steps: ['Slow cooked goat meat'] },
        { id: 'l14', name: 'Kadhi Pakora Rice', type: 'veg', calories: 450, protein: 12, carbs: 60, fats: 15, ingredients: ['Yogurt Curry', 'Gram Flour Fritters'], steps: ['Tangy curry with rice'] },
        { id: 'l15', name: 'Lemon Rice', type: 'veg', calories: 350, protein: 6, carbs: 60, fats: 10, ingredients: ['Rice', 'Lemon', 'Peanuts'], steps: ['Zesty South Indian rice'] },
        { id: 'l16', name: 'Palak Paneer Rice', type: 'veg', calories: 450, protein: 20, carbs: 40, fats: 20, ingredients: ['Spinach', 'Paneer', 'Rice'], steps: ['Greens gravy'] },
        { id: 'l17', name: 'Dal Makhani Roti', type: 'veg', calories: 500, protein: 18, carbs: 55, fats: 22, ingredients: ['Black Lentils', 'Roti 2'], steps: ['Creamy lentils'] },
        { id: 'l18', name: 'Keema Matar Roti', type: 'non-veg', calories: 500, protein: 30, carbs: 40, fats: 20, ingredients: ['Minced Meat', 'Peas', 'Roti'], steps: ['Spicy mince curry'] },
        { id: 'l19', name: 'Mushroom Masala', type: 'veg', calories: 350, protein: 10, carbs: 40, fats: 12, ingredients: ['Mushrooms', 'Roti 2'], steps: ['Spicy mushroom curry'] },
        { id: 'l20', name: 'Tinda/Lauki Sabzi', type: 'veg', calories: 300, protein: 5, carbs: 45, fats: 8, ingredients: ['Gourd Veggies', 'Roti 2'], steps: ['Light summer lunch'] },
        { id: 'l21', name: 'Sambhar Rice', type: 'veg', calories: 350, protein: 12, carbs: 60, fats: 5, ingredients: ['Lentil Stew', 'Rice', 'Veggies'], steps: ['Traditional South Indian'] },
        { id: 'l22', name: 'Prawns Curry Rice', type: 'non-veg', calories: 450, protein: 30, carbs: 55, fats: 12, ingredients: ['Prawns', 'Rice', 'Coconut'], steps: ['Coastal seafood curry'] },
        { id: 'l23', name: 'Aloo Gobi Roti', type: 'veg', calories: 350, protein: 8, carbs: 50, fats: 12, ingredients: ['Potato', 'Cauliflower', 'Roti'], steps: ['Dry vegetable fry'] },
        { id: 'l24', name: 'Methi Malai Matar', type: 'veg', calories: 450, protein: 12, carbs: 40, fats: 25, ingredients: ['Fenugreek', 'Peas', 'Cream', 'Roti'], steps: ['Rich white gravy'] },
        { id: 'l25', name: 'Chicken Stir Fry', type: 'non-veg', calories: 400, protein: 35, carbs: 20, fats: 15, ingredients: ['Chicken', 'Veggies'], steps: ['Low carb lunch'] }
    ],
    dinner: [
        { id: 'd1', name: 'Grilled Chicken Salad', type: 'non-veg', calories: 350, protein: 35, carbs: 10, fats: 15, ingredients: ['Chicken', 'Veggies'], steps: ['Grill & toss'] },
        { id: 'd2', name: 'Moong Dal Khichdi', type: 'veg', calories: 320, protein: 12, carbs: 50, fats: 8, ingredients: ['Rice', 'Dal', 'Ghee'], steps: ['Comfort food'] },
        { id: 'd3', name: 'Palak Paneer Roti', type: 'veg', calories: 350, protein: 18, carbs: 30, fats: 18, ingredients: ['Spinach', 'Paneer', 'Roti'], steps: ['Healthy greens'] },
        { id: 'd4', name: 'Grilled Fish Veggies', type: 'non-veg', calories: 300, protein: 30, carbs: 10, fats: 12, ingredients: ['Fish', 'Veggies'], steps: ['Light dinner'] },
        { id: 'd5', name: 'Lentil Soup Salad', type: 'veg', calories: 250, protein: 15, carbs: 35, fats: 5, ingredients: ['Dal Cup', 'Salad'], steps: ['Soup & salad'] },
        { id: 'd6', name: 'Chicken Stew', type: 'non-veg', calories: 400, protein: 28, carbs: 40, fats: 12, ingredients: ['Chicken', 'Veggies', 'Bread'], steps: ['Mild stew'] },
        { id: 'd7', name: 'Besan Bhindi Roti', type: 'veg', calories: 300, protein: 10, carbs: 40, fats: 10, ingredients: ['Okra', 'Roti 2'], steps: ['Crispy bhindi'] },
        { id: 'd8', name: 'Paneer Tikka Salad', type: 'veg', calories: 300, protein: 20, carbs: 15, fats: 15, ingredients: ['Paneer cubes', 'Veggies'], steps: ['Tandoori style'] },
        { id: 'd9', name: 'Oats Khichdi', type: 'veg', calories: 300, protein: 10, carbs: 45, fats: 8, ingredients: ['Oats', 'Dal', 'Veggies'], steps: ['High fiber dinner'] },
        { id: 'd10', name: 'Egg Salad', type: 'non-veg', calories: 250, protein: 18, carbs: 10, fats: 12, ingredients: ['Boiled Eggs 3', 'Veggies'], steps: ['Protein bowl'] },
        { id: 'd11', name: 'Chicken Tikka', type: 'non-veg', calories: 350, protein: 35, carbs: 10, fats: 15, ingredients: ['Chicken chunks', 'Yogurt'], steps: ['Clay oven style'] },
        { id: 'd12', name: 'Baingan Bharta', type: 'veg', calories: 300, protein: 5, carbs: 40, fats: 12, ingredients: ['Eggplant', 'Roti 2'], steps: ['Smoked eggplant mash'] },
        { id: 'd13', name: 'Daliya Pulao', type: 'veg', calories: 300, protein: 8, carbs: 50, fats: 6, ingredients: ['Broken Wheat', 'Veggies'], steps: ['Light pulao'] },
        { id: 'd14', name: 'Soya Chunk Salad', type: 'veg', calories: 250, protein: 20, carbs: 15, fats: 8, ingredients: ['Soya Chunks', 'Veggies'], steps: ['Boil & toss'] },
        { id: 'd15', name: 'Fish Fry (Shallow)', type: 'non-veg', calories: 350, protein: 30, carbs: 5, fats: 18, ingredients: ['Fish slices', 'Spices'], steps: ['Pan fry'] },
        { id: 'd16', name: 'Mix Veg Roti', type: 'veg', calories: 300, protein: 6, carbs: 45, fats: 10, ingredients: ['Seasonal Vegs', 'Roti 2'], steps: ['Homestyle sabzi'] },
        { id: 'd17', name: 'Quinoa Salad', type: 'veg', calories: 300, protein: 10, carbs: 45, fats: 8, ingredients: ['Quinoa', 'Veggies', 'Lemon'], steps: ['Superfood bowl'] },
        { id: 'd18', name: 'Chicken Soup', type: 'non-veg', calories: 200, protein: 20, carbs: 10, fats: 5, ingredients: ['Chicken Shreds', 'Broth'], steps: ['Clear soup'] },
        { id: 'd19', name: 'Tomato Soup & Toast', type: 'veg', calories: 180, protein: 4, carbs: 30, fats: 5, ingredients: ['Tomatoes', 'Bread'], steps: ['Creamy soup'] },
        { id: 'd20', name: 'Millet Roti & Dal', type: 'veg', calories: 350, protein: 15, carbs: 50, fats: 8, ingredients: ['Bajra Roti', 'Dal'], steps: ['Rural meal'] },
        { id: 'd21', name: 'Curd Rice (Light)', type: 'veg', calories: 300, protein: 8, carbs: 45, fats: 8, ingredients: ['Rice', 'Curd'], steps: ['Digestive dinner'] },
        { id: 'd22', name: 'Stuffed Capsicum', type: 'veg', calories: 300, protein: 10, carbs: 35, fats: 12, ingredients: ['Capsicum', 'Potato/Paneer'], steps: ['Baked/Cooked'] },
        { id: 'd23', name: 'Cauliflower Rice', type: 'veg', calories: 200, protein: 6, carbs: 20, fats: 10, ingredients: ['Grated Gobi', 'Spices'], steps: ['Keto friendly'] },
        { id: 'd24', name: 'Chilli Chicken (Dry)', type: 'non-veg', calories: 400, protein: 30, carbs: 20, fats: 15, ingredients: ['Chicken', 'Sauces'], steps: ['Indo-Chinese'] },
        { id: 'd25', name: 'Pumpkin Soup', type: 'veg', calories: 150, protein: 2, carbs: 25, fats: 5, ingredients: ['Pumpkin', 'Cream'], steps: ['Sweet & savory'] }
    ],
    snacks: [
        { id: 's1', name: 'Roasted Makhana', type: 'veg', calories: 100, protein: 3, carbs: 20, fats: 0, ingredients: ['Makhana'], steps: ['Dry roast'] },
        { id: 's2', name: 'Masala Chaas', type: 'veg', calories: 50, protein: 2, carbs: 5, fats: 2, ingredients: ['Curd', 'Water'], steps: ['Blend & spice'] },
        { id: 's3', name: 'Roasted Chana', type: 'veg', calories: 150, protein: 6, carbs: 20, fats: 4, ingredients: ['Chana'], steps: ['Ready snack'] },
        { id: 's4', name: 'Fruit Bowl', type: 'veg', calories: 120, protein: 1, carbs: 30, fats: 0, ingredients: ['Fruits'], steps: ['Chop fresh'] },
        { id: 's5', name: 'Egg Whites', type: 'non-veg', calories: 50, protein: 11, carbs: 1, fats: 0, ingredients: ['Eggs 3'], steps: ['Boil & peel'] },
        { id: 's6', name: 'Peanut Salad', type: 'veg', calories: 200, protein: 8, carbs: 10, fats: 15, ingredients: ['Peanuts', 'Veggies'], steps: ['Mix & eat'] },
        { id: 's7', name: 'Green Tea & Almonds', type: 'veg', calories: 100, protein: 4, carbs: 5, fats: 8, ingredients: ['Almonds 10', 'Tea'], steps: ['Sip & munch'] },
        { id: 's8', name: 'Cucumber Slices', type: 'veg', calories: 30, protein: 1, carbs: 5, fats: 0, ingredients: ['Cucumber'], steps: ['Slice & chat masala'] },
        { id: 's9', name: 'Protein Shake', type: 'veg', calories: 120, protein: 24, carbs: 3, fats: 1, ingredients: ['Whey', 'Water'], steps: ['Shake well'] },
        { id: 's10', name: 'Coconut Water', type: 'veg', calories: 40, protein: 0, carbs: 10, fats: 0, ingredients: ['Fresh Water'], steps: ['Hydrate'] },
        { id: 's11', name: 'Popcorn (Plain)', type: 'veg', calories: 100, protein: 3, carbs: 20, fats: 1, ingredients: ['Corn'], steps: ['Air pop'] },
        { id: 's12', name: 'Yogurt Bowl', type: 'veg', calories: 120, protein: 8, carbs: 15, fats: 4, ingredients: ['Curd', 'Berries'], steps: ['Mix fruit in dahi'] },
        { id: 's13', name: 'Hummus & Sticks', type: 'veg', calories: 180, protein: 6, carbs: 20, fats: 10, ingredients: ['Hummus', 'Carrot'], steps: ['Dip & eat'] },
        { id: 's14', name: 'Bhel Puri (Dry)', type: 'veg', calories: 200, protein: 5, carbs: 40, fats: 5, ingredients: ['Puffed Rice', 'Veggies'], steps: ['No chutney mix'] },
        { id: 's15', name: 'Corn Chaat', type: 'veg', calories: 150, protein: 4, carbs: 30, fats: 2, ingredients: ['Boiled Corn', 'Lemon'], steps: ['Spicy corn mix'] },
        { id: 's16', name: 'Sweet Potato', type: 'veg', calories: 150, protein: 2, carbs: 35, fats: 0, ingredients: ['Sweet Potato'], steps: ['Boil & roast'] },
        { id: 's17', name: 'Murmura Chivda', type: 'veg', calories: 150, protein: 3, carbs: 25, fats: 5, ingredients: ['Puffed Rice', 'Spice'], steps: ['Dry snack'] },
        { id: 's18', name: 'Cheese Slice', type: 'veg', calories: 80, protein: 5, carbs: 1, fats: 6, ingredients: ['Cheese'], steps: ['Quick bite'] },
        { id: 's19', name: 'Soya Sticks', type: 'veg', calories: 150, protein: 8, carbs: 20, fats: 6, ingredients: ['Soya sticks'], steps: ['Baked snack'] },
        { id: 's20', name: 'Dark Chocolate', type: 'veg', calories: 100, protein: 1, carbs: 10, fats: 8, ingredients: ['70% Chocolate'], steps: ['Small piece'] }
    ]
};
